name: dermaininstitute
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_screenutil: ^5.9.3
  
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0
  shared_preferences: ^2.3.2
  image_picker: ^1.2.0
  dropdown_model_list: ^3.0.2
  flutter_advanced_avatar: ^1.5.2

  connectivity_plus: ^6.1.5

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  pin_code_fields: ^8.0.1
  flutter_easyloading: ^3.0.5
  shimmer: ^3.0.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  http_parser: ^4.1.2
  path: ^1.9.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/applogo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/applogo.png"


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/